version: '3.8'

services:
  monitor:
    build:
      context: ./MAPE-K/Monitor
      dockerfile: Dockerfile
    networks:
      - univaq-net

  analyzer:
    build:
      context: ./MAPE-K/Analysis
      dockerfile: Dockerfile
    networks:
      - univaq-net

  planner_ventilation:
    build:
      context: ./MAPE-K/Planning/Planning_ventilation
      dockerfile: Dockerfile
    networks:
      - univaq-net

  planner_actuatorcommands:
    build:
      context: ./MAPE-K/Planning/Planning_ActuatorCommands
      dockerfile: Dockerfile
    networks:
      - univaq-net    

  executor_ventilation:
    build:
      context: ./MAPE-K/Execution/Execution_ventilation
      dockerfile: Dockerfile
    networks:
      - univaq-net

  executor_actuatorcommands:
    build:
      context: ./MAPE-K/Execution/Execution_ActuatorCommands
      dockerfile: Dockerfile
    networks:
      - univaq-net      

  nodered:
    image: adambouafia/gaz_univaq_image:latest
    ports:
      - "1880:1880"
    networks:
      - univaq-net

  influxdb:
    image: influxdb:2.7.5
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=adam.bouafia
      - DOCKER_INFLUXDB_INIT_PASSWORD=00000000
      - DOCKER_INFLUXDB_INIT_ORG=A&R
      - DOCKER_INFLUXDB_INIT_BUCKET=SHS
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=YtSTZaPMzl8nI1WCfL0CNOPAn4sPgmzcO2FGMxiYTiq6We6BzB1tAygP55pBl3Kht_mGpNfkbHPCb1Vtyo96UQ==
    networks:
      - univaq-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-gaz-dashboard:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb
    networks:
      - univaq-net

volumes:
  influxdb-data:
  grafana-data:

networks:
  univaq-net:
